### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by fwhelan** [claczny/VizBin#29]
Hi claczny- thanks for creating such an interesting tool. I'm very curious to give it a try. I have tried downloading both the stand alone via the "Download app" on your homepage as well as cloned your github repository and am running into trouble.

Double-clicking the .jar does nothing; ```java -jar VisBin-dist.jar``` produces

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: lu/uni/lcsb/vizbin/Main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: lu.uni.lcsb.vizbin.Main. Program will exit.
```

Any advice would be great.

**Comment by claczny** [comment]
Hi @fwhelan,

thank you for your interest in VizBin.
The issue you are experiencing appears to be related to an older Java installation of yours, i.e., prior to Java 7.
Could you please check your Java version and let me know if it is < v.7?
VizBin requires Java >= v.7.

Should your Java version be < v.7, an update, even just for security reasons, might be suggested anyways ;)

**Comment by fwhelan** [comment]
Gah sorry- dumb mistake! Works perfectly now.

Thanks for your help!

**Comment by claczny** [comment]
Sure, no problem and good to hear that it works now :)
Happy to help.

Please note that your experiences in using VizBin are greatly appreciated, i.e., the positive ones as well as the negative ones.
Actually, the negative ones are to some extent even more insightful as that enables us to further improve VizBin ;)
Feel free to drop them here.

**Comment by fwhelan** [comment]
Will do!
